export const nomenclature={
 PRODUCT_NAME:"Proof Of Kindness",
 HOME:'Home',
 EXPLORE_CAMPAIGNS:"Explore Campaigns",
 ABOUT_US:"About Us",
 SIGN_IN:"Sign In",
 SIGNING_IN:"Signing In...",
 SIGN_UP:"Sign Up",
 SIGNING_UP:"Signing Up...",
 SIGN_OUT:"Sign Out",
 NGO_PORTAL:"NGO Portal",
 SOC_2_COMPLIANT:"🔒 SOC 2 COMPLIANT",
 END_TO_END_ENCRYPTED:"🔒 END-TO-END ENCRYPTED",
 COPYRIGHT:"© 2026 Proof of Kindness. Secure Crypto-Philanthropy. All rights reserved.",
 ORGANIZATION_LOGIN:"Organization Login",
 ORGANIZATION_LOGIN_DESCRIPTION:"Access your impact dashboard securely using your decentralized identity.",
 NEW_TO_POK:"New to Proof of Kindness ecosystem?",
 NGO_REGISTRATION:"NGO Registration",
 NGO_REGISTRATION_DESCRIPTION:"Join the Proof of Kindness network to unlock transparent, blockchain-verified donations for your cause.",
 SECURE_VERIFICATION:"Secure Verification",
 SECURE_VERIFICATION_DESCRIPTION:"Your registration will be audited by the PoK protocol to ensure compliance with global non-profit standards.",
 ORGANIZATION_DETAILS:"Step 1: Organization Details",
 ORGANIZATION_DETAILS_DESCRIPTION:"Provide your legal entity information to verify your identity and compliance with global non-profit standards.",
 MISSION_DETAILS:"Step 2: Mission & Causes",
 MISSION_DETAILS_DESCRIPTION:"Tell us about the change you want to see in the world.",
 MISSION_STATEMENT:"Mission Statement",
 GOAL_AMOUNT:"Goal Amount",
 MISSION_STATEMENT_PLACEHOLDER:"Describe your NGO's primary goals, target community, and the change you aim to create...",
 CAUSE:"Cause",
 CAUSE_PLACEHOLDER:"Write your cause here...",
 DONATION_AMOUNT:"Donation Amount",
 WALLET_SETUP:"Step 3: Wallet Setup",
 WALLET_SETUP_DESCRIPTION:"Choose how you would like to receive donations.",
 PROTOCOL_TRANSPARENCY:"Protocol Transparency",
 ENTER_FULL_NAME:"Enter your full name",
 ENTER_EMAIL:"Enter your email address",
 ENTER_PASSWORD:"Enter your password",
 ENTER_PHONE:"Enter your phone number",
 FORGOT:"Forgot? ",
 JOIN_THE_MOVEMENT:"Join 4,000+ donors who have abandoned traditional charity for high-frequency on-chain philanthropy.",
 ABOUT_DESCRIPTION:"Empowering digital authenticity through secure blockchain technology. We are building the infrastructure for a world where every contribution is verifiable and every impact is measurable.",
 HOME_BADGE:"SOC2 Type II Certified Security",
 DONATE:"Start Donating",
 REGISTER:"Register as NGO",
 PHILANTHROPY:"Re-engineering Philanthropy",
 PHILANTHROPY_PARA:"We use zero-knowledge proofs to solve the three biggest hurdles in global giving.",
 CONTRIBUTE:"Anonymous Contributions",
 CONTRIBUTE_PARA:"Donate without revealing your identity or wallet address. Using ZK-Snarks, we ensure your privacy while maintaining a clear audit trail for the receiving NGO.",
 ZERO_FEES:"Near-Zero Fees",
 ZERO_FEES_PARA:"Avoid the 5–10% overhead of traditional platforms. PhilanthroChain leverages L2 tech to keep fees under 0.1%.",
 IMPACT_PARA:" Track every dollar from transaction to on-the-ground execution via immutable smart contract milestones.",
 IMPACT_READY_PARA:"Join over 50,000 anonymous donors who are changing the world through transparent crypto philanthropy.",
 HOME_PARA:"The first decentralized custodian platform enabling secure, private, and verifiable crypto contributions to vetted NGOs worldwide with near-zero fees.",
 OVERVIEW:"Overview",
 ACTIVE_CAUSES:"Active Causes",
 DONATION_HISTORY:"Donation History",
 WITHDRAW_FUNDS:"Withdraw funds",
 POST_A_CAUSE:"Post a New Cause",
 BASIC_INFORMATION:"Basic Information",
 CAMPAIGN_VISUALS:"Campaign Visuals",
 FINANCIALS:"Financials",
 WHY:"The 'Why' & Strategy"
}