export const nomenclature={
 PRODUCT_NAME:"Proof Of Kindness",
 HOME:'Home',
 EXPLORE_CAMPAIGNS:"Explore Campaigns",
 ABOUT_US:"About Us",
 SIGN_IN:"Sign In",
 SIGNING_IN:"Signing In...",
 SIGN_UP:"Sign Up",
 SIGNING_UP:"Signing Up...",
 NGO_PORTAL:"NGO Portal",
 SOC_2_COMPLIANT:"🔒 SOC 2 COMPLIANT",
 END_TO_END_ENCRYPTED:"🔒 END-TO-END ENCRYPTED",
 COPYRIGHT:"© 2026 Proof of Kindness. Secure Crypto-Philanthropy. All rights reserved.",
 ORGANIZATION_LOGIN:"Organization Login",
 ORGANIZATION_LOGIN_DESCRIPTION:"Access your impact dashboard securely using your decentralized identity.",
 NEW_TO_POK:"New to Proof of Kindness ecosystem?",
 NGO_REGISTRATION:"NGO Registration",
 NGO_REGISTRATION_DESCRIPTION:"Join the Proof of Kindness network to unlock transparent, blockchain-verified donations for your cause.",
 SECURE_VERIFICATION:"Secure Verification",
 SECURE_VERIFICATION_DESCRIPTION:"Your registration will be audited by the PoK protocol to ensure compliance with global non-profit standards.",
 ORGANIZATION_DETAILS:"Step 1: Organization Details",
 ORGANIZATION_DETAILS_DESCRIPTION:"Provide your legal entity information to verify your identity and compliance with global non-profit standards.",
 MISSION_DETAILS:"Step 2: Mission & Causes",
 MISSION_DETAILS_DESCRIPTION:"Tell us about the change you want to see in the world.",
 MISSION_STATEMENT:"Mission Statement",
 MISSION_STATEMENT_PLACEHOLDER:"Describe your NGO's primary goals, target community, and the change you aim to create...",
 CAUSE:"Cause",
 CAUSE_PLACEHOLDER:"Write your cause here...",
 DONATION_AMOUNT:"Donation Amount",
 WALLET_SETUP:"Step 3: Wallet Setup",
 WALLET_SETUP_DESCRIPTION:"Choose how you would like to receive donations.",
 PROTOCOL_TRANSPARENCY:"Protocol Transparency",
 ENTER_FULL_NAME:"Enter your full name",
 ENTER_EMAIL:"Enter your email address",
 ENTER_PASSWORD:"Enter your password",
 ENTER_PHONE:"Enter your phone number",
 JOIN_THE_MOVEMENT:"Join 4,000+ donors who have abandoned traditional charity for high-frequency on-chain philanthropy.",
 ABOUT_DESCRIPTION:"Empowering digital authenticity through secure blockchain technology. We are building the infrastructure for a world where every contribution is verifiable and every impact is measurable."
}