import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "../../globals.css";
import NGOHeader from "@/components/NGOHeader";
import Footer from "@/components/Footer";
import { Sidebar, SidebarProvider } from "@/components/ui/sidebar";
import AppSidebar from "@/components/AppSidebar";


const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  weight: ["800", "700", "600", "400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function NGOLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const isLoggedIn = true;
  return (
        <SidebarProvider>
      <div className="flex w-full">
                {/* Sidebar ONLY if logged in */}
        {isLoggedIn &&<Sidebar /> }
        <div>
        <NGOHeader isLoggedIn={isLoggedIn} pageTitle={"Dashboard Overview"} walletAddress={"0x1234"} />
              <main className="flex-1 bg-background overflow-y-auto p-4 h-screen">
                {children}
              </main>
        <Footer />
        </div>
      </div>
      </SidebarProvider>
  );
}
