import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "../../globals.css";
import { Sidebar, SidebarProvider } from "@/src/components/ui/sidebar";
import NGOHeader from "@/src/components/NGOHeader";
import Footer from "@/src/components/Footer";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  weight: ["800", "700", "600", "400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function NGOLayout({ children }: { children: React.ReactNode }) {
  const isLoggedIn = false;
  return (
    <SidebarProvider>
      <div className={`flex w-full ${!isLoggedIn && "flex-col"}`}>
        {/* Sidebar ONLY if logged in */}
        {isLoggedIn && <Sidebar className="sm:display-none" />}
        <div>
          <NGOHeader
            isLoggedIn={isLoggedIn}
            pageTitle={"Dashboard Overview"}
            walletAddress={"0x1234"}
          />
          <main className="bg-background w-full overflow-y-auto p-4">
            {children}
          </main>
          <Footer />
        </div>
      </div>
    </SidebarProvider>
  );
}
