import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import Providers from "../components/Providers";
import { Toaster } from "../components/ui/sonner";
import GlobalLoader from "../components/GlobalLoader";
const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  weight: ["800", "700", "600", "400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${manrope.variable} h-full antialiased`}>
      <head>
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/favicon/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon/favicon-16x16.png"
        />
        <link rel="manifest" href="/favicon/site.webmanifest" />
      </head>
      <body className="min-h-full">
        <Providers>
          {children}
          <GlobalLoader />
        </Providers>
        <Toaster richColors={true} position="top-center" theme="light" />
      </body>
    </html>
  );
}
